version: '2'
services:
  lunchqian_api:
    build: .
    ports:
      - "9000:9000"
    command: "revel run github.com/lunchqian-api"
  couch_db:
    image: apache/couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couch_db:/opt/couchdb/data
volumes:
  couch_db: {}
