version: '2'
services:
  couch_db:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couch_db:/usr/local/var/lib/couchdb
volumes:
  couch_db: {}
